import { Anime, Episode, AppTranslation } from './types';

export const TRANSLATIONS: Record<'en' | 'hi', AppTranslation> = {
  en: {
    appName: "Ankit's Anime",
    searchPlaceholder: "Search anime, movies, genres...",
    trending: "Trending Now",
    popular: "Most Popular",
    newReleases: "New Releases",
    movies: "Anime Movies",
    continueWatching: "Continue Watching",
    episodes: "Episodes",
    watchlist: "Watchlist",
    history: "History",
    downloads: "Downloads",
    offline: "Offline Library",
    profile: "Profile",
    settings: "Settings",
    language: "App Language",
    theme: "Visual Theme",
    logout: "Log Out",
    guestMode: "Guest Mode",
    login: "Log In",
    search: "Search",
    genres: "Genres",
    status: "Status",
    year: "Release Year",
    type: "Format",
    ongoing: "Ongoing",
    completed: "Completed",
    addToWatchlist: "Add to Watchlist",
    removeFromWatchlist: "Remove Watchlist",
    downloadEpisode: "Download",
    downloading: "Downloading...",
    downloaded: "Downloaded",
    paused: "Paused",
    resume: "Resume",
    pause: "Pause",
    offlineLibrary: "Downloaded Offline Content",
    level: "Otaku Level",
    xp: "XP",
    stats: "Viewing Stats",
    episodesFinished: "Episodes Finished",
    timeWatched: "Time Spent Watching",
    hours: "hours",
    noDownloadsYet: "Your Offline Library is Empty",
    noDownloadsDesc: "Download episodes while connected to the internet to watch them anywhere, completely offline!",
    noWatchlistYet: "Nothing in your Watchlist",
    noWatchlistDesc: "Tap the watchlist icon on your favorite anime to keep track of what you want to watch next.",
    noHistoryYet: "No Viewing History",
    noHistoryDesc: "Anime you watch will appear here, allowing you to easily resume from where you left off.",
    watchNow: "Watch Now",
    nowPlaying: "Now Streaming",
    audioTrack: "Audio Track",
    subtitles: "Subtitles",
    quality: "Video Quality",
    backToBrowse: "Back to Browse",
    animeDetails: "Anime Details",
    english: "English",
    hindi: "Hindi",
    darkTheme: "Premium Dark",
    lightTheme: "Clean Light",
    guestWarning: "Logged in as Guest. Some features are simulated.",
    filterBy: "Filter By",
    sortBy: "Sort By",
    resetFilters: "Reset Filters"
  },
  hi: {
    appName: "अंकित का एनीमे",
    searchPlaceholder: "एनीमे, फिल्में, शैलियों खोजें...",
    trending: "अभी चलन में",
    popular: "सबसे लोकप्रिय",
    newReleases: "नए रिलीज",
    movies: "एनीमे फिल्में",
    continueWatching: "देखना जारी रखें",
    episodes: "एपिसोड",
    watchlist: "मेरी सूची",
    history: "इतिहास",
    downloads: "डाउनलोड",
    offline: "ऑफ़लाइन लाइब्रेरी",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    language: "ऐप की भाषा",
    theme: "विज़ुअल थीम",
    logout: "लॉग आउट",
    guestMode: "अतिथि मोड",
    login: "लॉग इन करें",
    search: "खोजें",
    genres: "शैलियाँ",
    status: "स्थिति",
    year: "रिलीज का वर्ष",
    type: "प्रारूप",
    ongoing: "जारी है",
    completed: "पूर्ण",
    addToWatchlist: "सूची में जोड़ें",
    removeFromWatchlist: "सूची से हटाएं",
    downloadEpisode: "डाउनलोड",
    downloading: "डाउनलोड हो रहा है...",
    downloaded: "डाउनलोड किया गया",
    paused: "रुका हुआ",
    resume: "फिर शुरू करें",
    pause: "रोकें",
    offlineLibrary: "डाउनलोड की गई ऑफ़लाइन सामग्री",
    level: "ओटाकू स्तर",
    xp: "एक्सपी",
    stats: "देखने के आंकड़े",
    episodesFinished: "पूरे किए गए एपिसोड",
    timeWatched: "देखने में बिताया गया समय",
    hours: "घंटे",
    noDownloadsYet: "आपकी ऑफ़लाइन लाइब्रेरी खाली है",
    noDownloadsDesc: "इंटरनेट से कनेक्ट होने पर एपिसोड डाउनलोड करें ताकि आप उन्हें कहीं भी, पूरी तरह से ऑफ़लाइन देख सकें!",
    noWatchlistYet: "आपकी सूची में कुछ नहीं है",
    noWatchlistDesc: "आगे क्या देखना है, इस पर नज़र रखने के लिए अपने पसंदीदा एनीमे पर सूची आइकन दबाएं।",
    noHistoryYet: "कोई देखने का इतिहास नहीं",
    noHistoryDesc: "आपके द्वारा देखे जाने वाले एनीमे यहां दिखाई देंगे, जिससे आप आसानी से वहीं से शुरू कर सकते हैं जहां आपने छोड़ा था।",
    watchNow: "अभी देखें",
    nowPlaying: "अभी स्ट्रीम हो रहा है",
    audioTrack: "ऑडियो ट्रैक",
    subtitles: "उपशीर्षक",
    quality: "वीडियो क्वालिटी",
    backToBrowse: "ब्राउज़ पर वापस जाएं",
    animeDetails: "एनीमे विवरण",
    english: "अंग्रेजी (English)",
    hindi: "हिंदी (Hindi)",
    darkTheme: "प्रीमियम डार्क",
    lightTheme: "क्लीन लाइट",
    guestWarning: "अतिथि के रूप में लॉग इन किया गया। कुछ सुविधाएं सिम्युलेटेड हैं।",
    filterBy: "फ़िल्टर करें",
    sortBy: "क्रमबद्ध करें",
    resetFilters: "फ़िल्टर रीसेट करें"
  }
};

export const ANIME_DATA: Anime[] = [
  {
    id: "anime-1",
    title: "Cyberpunk: Neo-Delhi",
    titleHindi: "साइबरपंक: नियो-दिल्ली",
    rating: 4.9,
    episodesCount: 12,
    genres: ["Sci-Fi", "Cyberpunk", "Action"],
    genresHindi: ["विज्ञान-कल्पना", "साइबरपंक", "ऐक्शन"],
    description: "In the neon-drenched streets of future Neo-Delhi, a brilliant street kid attempts to survive by becoming a high-tech outlaw known as a Cyber-runner, modifying his body with cybernetic enhancements.",
    descriptionHindi: "भविष्य के नियो-दिल्ली की नियॉन-रोशन गलियों में, एक प्रतिभाशाली अनाथ लड़का खुद को साइबरनेटिक संवर्द्धन के साथ बदलकर एक हाई-टेक अपराधी (साइबर-रनर) बनता है और जीवित रहने का प्रयास करता है।",
    banner: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=400&auto=format&fit=crop",
    status: "Completed",
    releaseYear: "2026",
    type: "Series",
    popularity: 98,
    trending: true,
    newRelease: false
  },
  {
    id: "anime-2",
    title: "Shadow of the Shogun",
    titleHindi: "शोगुन की छाया",
    rating: 4.8,
    episodesCount: 24,
    genres: ["Action", "Historical", "Samurai", "Fantasy"],
    genresHindi: ["ऐक्शन", "ऐतिहासिक", "सामुराई", "फंतासी"],
    description: "A rogue samurai with a cursed sword travels across historical feudal India-Japan fusion land, defending innocent villagers from demonic spirits sent by a mysterious dark Shogun.",
    descriptionHindi: "एक शापित तलवार वाला बागी सामुराई भारत-जापान संलयन वाली सामंती भूमि पर यात्रा करता है, और एक रहस्यमयी दुष्ट शोगुन द्वारा भेजे गए शैतानी आत्माओं से मासूम ग्रामीणों की रक्षा करता है।",
    banner: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=400&auto=format&fit=crop",
    status: "Ongoing",
    releaseYear: "2026",
    type: "Series",
    popularity: 95,
    trending: true,
    newRelease: true
  },
  {
    id: "anime-3",
    title: "Skyward Velocity: Drift",
    titleHindi: "आकाशीय गति: ड्रिफ्ट",
    rating: 4.6,
    episodesCount: 13,
    genres: ["Sports", "Racing", "Drama"],
    genresHindi: ["खेल", "रेसिंग", "ड्रामा"],
    description: "An aspiring high-altitude hover-car racer from the slums gets a lifetime chance to join the Royal Grand Prix, competing against elite drivers with cutting-edge anti-gravity engines.",
    descriptionHindi: "झुग्गी-झोपड़ियों का एक महत्वाकांक्षी हाई-एल्टीट्यूड होवर-कार रेसर शाही ग्रैंड प्रिक्स में शामिल होने का जीवन भर का मौका पाता है, और अत्याधुनिक एंटी-ग्रेविटी इंजनों वाले कुलीन ड्राइवरों के खिलाफ प्रतिस्पर्धा करता है।",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop",
    status: "Ongoing",
    releaseYear: "2026",
    type: "Series",
    popularity: 91,
    trending: false,
    newRelease: true
  },
  {
    id: "anime-4",
    title: "My Celestial Classmate",
    titleHindi: "मेरी दिव्य सहपाठी",
    rating: 4.7,
    episodesCount: 12,
    genres: ["Romance", "Comedy", "Slice of Life"],
    genresHindi: ["रोमांस", "कॉमेडी", "स्लाइस ऑफ लाइफ"],
    description: "Average high school student Kabir finds his life turned upside down when a beautiful celestial guardian princess is transferred to his class to protect him from galactic anomalies.",
    descriptionHindi: "एक साधारण हाई स्कूल के छात्र कबीर का जीवन तब बदल जाता है जब एक सुंदर दिव्य रक्षक राजकुमारी का उसकी कक्षा में तबादला कर दिया जाता है ताकि वह उसे ब्रह्मांडीय विसंगतियों से बचा सके।",
    banner: "https://images.unsplash.com/photo-1528360983277-13d401ccd795?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1528360983277-13d401ccd795?q=80&w=400&auto=format&fit=crop",
    status: "Completed",
    releaseYear: "2025",
    type: "Series",
    popularity: 88,
    trending: false,
    newRelease: false
  },
  {
    id: "anime-5",
    title: "The Iron Alchemist",
    titleHindi: "द आयरन अल्केमिस्ट",
    rating: 4.9,
    episodesCount: 64,
    genres: ["Fantasy", "Action", "Adventure", "Steampunk"],
    genresHindi: ["फंतासी", "ऐक्शन", "साहसिक", "स्टीमपंक"],
    description: "Two brothers use forbidden alchemical arts to restore their physical forms after a tragic accident. Their journey leads them to discover a dark state conspiracy threatening the continent.",
    descriptionHindi: "एक दर्दनाक दुर्घटना के बाद अपने शरीर को बहाल करने के लिए दो भाई वर्जित कीमिया कला का उपयोग करते हैं। उनकी यात्रा उन्हें महाद्वीप को खतरे में डालने वाली एक गहरी साजिश का पता लगाने की ओर ले जाती है।",
    banner: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=400&auto=format&fit=crop",
    status: "Completed",
    releaseYear: "2024",
    type: "Series",
    popularity: 97,
    trending: false,
    newRelease: false
  },
  {
    id: "anime-6",
    title: "Whisper of the Wind",
    titleHindi: "हवा की सरसराहट",
    rating: 4.9,
    episodesCount: 1,
    genres: ["Fantasy", "Adventure", "Drama"],
    genresHindi: ["फंतासी", "साहसिक", "ड्रामा"],
    description: "An awe-inspiring theatrical movie. A young girl from a floating island valley boards an enchanted airship to find the source of the wind whisper, which holds the key to curing her village's drought.",
    descriptionHindi: "एक विस्मयकारी नाटकीय फिल्म। एक तैरते हुए द्वीप घाटी की एक युवा लड़की हवा की सरसराहट के स्रोत को खोजने के लिए एक जादुई हवाई जहाज पर सवार होती है, जो उसके गांव के सूखे को दूर करने की कुंजी है।",
    banner: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400&auto=format&fit=crop",
    status: "Completed",
    releaseYear: "2025",
    type: "Movie",
    popularity: 94,
    trending: true,
    newRelease: false
  },
  {
    id: "anime-7",
    title: "Demon Slayer: Infinite Realm",
    titleHindi: "डेमन स्लेयर: अनंत क्षेत्र",
    rating: 4.8,
    episodesCount: 1,
    genres: ["Action", "Fantasy", "Historical"],
    genresHindi: ["ऐक्शन", "फंतासी", "ऐतिहासिक"],
    description: "In this thrilling movie, the demon-hunting squad boards a ghost train heading to a realm where space and time fold, facing the highest rank demon who controls dreams and nightmares.",
    descriptionHindi: "इस रोमांचक फिल्म में, दानव-शिकारी दस्ता एक भूतिया ट्रेन पर सवार होता है, जो एक ऐसे क्षेत्र की ओर जाती है जहां स्थान और समय सिकुड़ जाते हैं, जहां वे सपनों और दुःस्वप्नों को नियंत्रित करने वाले सर्वोच्च श्रेणी के दानव का सामना करते हैं।",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400&auto=format&fit=crop",
    status: "Completed",
    releaseYear: "2026",
    type: "Movie",
    popularity: 99,
    trending: true,
    newRelease: true
  }
];

export const EPISODE_DATA: Record<string, Episode[]> = {
  "anime-1": [
    {
      id: "ep-1-1",
      animeId: "anime-1",
      episodeNumber: 1,
      title: "Chipped Chrome",
      titleHindi: "टूटा हुआ क्रोम",
      duration: "24m",
      thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
    },
    {
      id: "ep-1-2",
      animeId: "anime-1",
      episodeNumber: 2,
      title: "Neon Outlaw",
      titleHindi: "नियॉन अपराधी",
      duration: "23m",
      thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutback.mp4"
    },
    {
      id: "ep-1-3",
      animeId: "anime-1",
      episodeNumber: 3,
      title: "Grid runner",
      titleHindi: "ग्रिड रनर",
      duration: "24m",
      thumbnail: "https://images.unsplash.com/photo-1528360983277-13d401ccd795?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
    }
  ],
  "anime-2": [
    {
      id: "ep-2-1",
      animeId: "anime-2",
      episodeNumber: 1,
      title: "The Cursed Steel",
      titleHindi: "शापित इस्पात",
      duration: "23m",
      thumbnail: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    },
    {
      id: "ep-2-2",
      animeId: "anime-2",
      episodeNumber: 2,
      title: "Monsters at Twilight",
      titleHindi: "गोधूलि वेला के दानव",
      duration: "24m",
      thumbnail: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
    }
  ],
  "anime-3": [
    {
      id: "ep-3-1",
      animeId: "anime-3",
      episodeNumber: 1,
      title: "Terminal Velocity",
      titleHindi: "अंतिम वेग",
      duration: "24m",
      thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
    },
    {
      id: "ep-3-2",
      animeId: "anime-3",
      episodeNumber: 2,
      title: "Apex Cornering",
      titleHindi: "सर्वोच्च कोना",
      duration: "25m",
      thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
    }
  ],
  "anime-4": [
    {
      id: "ep-4-1",
      animeId: "anime-4",
      episodeNumber: 1,
      title: "Arrival from the Stars",
      titleHindi: "सितारों से आगमन",
      duration: "24m",
      thumbnail: "https://images.unsplash.com/photo-1528360983277-13d401ccd795?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"
    }
  ],
  "anime-5": [
    {
      id: "ep-5-1",
      animeId: "anime-5",
      episodeNumber: 1,
      title: "The Law of Exchange",
      titleHindi: "समान विनिमय का नियम",
      duration: "23m",
      thumbnail: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
    }
  ],
  "anime-6": [
    {
      id: "ep-6-1",
      animeId: "anime-6",
      episodeNumber: 1,
      title: "Whisper of the Wind (Full Movie)",
      titleHindi: "हवा की सरसराहट (पूरी फिल्म)",
      duration: "1h 45m",
      thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"
    }
  ],
  "anime-7": [
    {
      id: "ep-7-1",
      animeId: "anime-7",
      episodeNumber: 1,
      title: "Infinite Realm (Full Movie)",
      titleHindi: "अनंत क्षेत्र (पूरी फिल्म)",
      duration: "1h 58m",
      thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=400&auto=format&fit=crop",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
    }
  ]
};

export const ALL_GENRES = ["Action", "Sci-Fi", "Fantasy", "Cyberpunk", "Historical", "Samurai", "Sports", "Racing", "Romance", "Comedy", "Slice of Life", "Adventure", "Steampunk"];
export const ALL_GENRES_HINDI = ["ऐक्शन", "विज्ञान-कल्पना", "फंतासी", "साइबरपंक", "ऐतिहासिक", "सामुराई", "खेल", "रेसिंग", "रोमांस", "कॉमेडी", "स्लाइस ऑफ लाइफ", "साहसिक", "स्टीमपंक"];
export const ALL_TYPES = ["Series", "Movie"];
